name: Rails RSpec
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: myapp
          POSTGRES_DB: myapp_test
          POSTGRES_PASSWORD: ""
        ports: ["5432:5432"]

    steps:
      # ref:https://github.com/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v2
      # ref:https://github.com/actions/setup-ruby
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      # ref:https://github.com/actions/cache/blob/main/examples.md#ruby---bundler
      - name: Ruby Bundler
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      # # https://github.com/actions/cache/blob/main/examples.md#node---yarn
      # - name: Get yarn cache directory path
      #   id: yarn-cache-dir-path
      #   run: echo "::set-output name=dir::$(yarn cache dir)"
      # - uses: actions/cache@v2
      #   id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      #   with:
      #     path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
      #     key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-yarn-
      # - name: yarn install
      #   run: yarn install
      # - name: set database.yml
      #   run: cp -v config/database.ci.yml config/database.yml
      # - name: db create
      #   run: bundle exec rails db:create db:schema:load --trace
      # - name: run rspec
      #   run: bundle exec rspec
      # - name: Archive rspec result screenshots
      #   if: failure()
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: rspec result screenshots
      #     path: tmp/screenshots/
